[theme]
base="dark"
primaryColor="#ffffffff"  # Neon green
backgroundColor="#000010"  # Deep space black-blue
secondaryBackgroundColor="#111122"  # Very dark indigo for content blocks
textColor="#eaeaea"  # Soft bright gray
font="Times New Roman"
